-- LOGIWISE 스키마
-- PRD 7.1 의 12개 테이블 + 에이전트용 추가 테이블 3개(AGENT_RUN, MON_ALERT, WF_DRAFT)
-- 코드 자릿수(CENTER 4, VENDOR 6, PRODUCT 10)는 SQLite가 강제하지 않으므로 settings.normalize_code 로 검증한다.
-- 날짜/시각은 KST 기준 ISO 문자열('YYYY-MM-DD', 'YYYY-MM-DD HH:MM:SS')로 저장한다.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------- 마스터
CREATE TABLE IF NOT EXISTS MT_CENTER (
    CENTER_CODE   TEXT PRIMARY KEY,            -- 4자리 (C001)
    CENTER_NAME   TEXT NOT NULL,
    REGION        TEXT NOT NULL,
    MANAGER_NAME  TEXT,
    PHONE         TEXT,
    CREATED_AT    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MT_VENDOR (
    VENDOR_CODE   TEXT PRIMARY KEY,            -- 6자리 (V00001)
    VENDOR_NAME   TEXT NOT NULL,
    VENDOR_TYPE   TEXT NOT NULL,               -- 제조사/유통사
    CREATED_AT    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MT_PRODUCT (
    PRODUCT_CODE  TEXT PRIMARY KEY,            -- 10자리 (0000000001)
    PRODUCT_NAME  TEXT NOT NULL,
    VENDOR_CODE   TEXT NOT NULL REFERENCES MT_VENDOR(VENDOR_CODE),
    CATEGORY      TEXT NOT NULL,
    UNIT          TEXT NOT NULL DEFAULT 'EA',
    UNIT_PRICE    INTEGER NOT NULL DEFAULT 0,
    CREATED_AT    TEXT NOT NULL
);

-- 공통코드: 이벤트유형/이상유형/조치유형/워크플로우상태/우선순위 등
CREATE TABLE IF NOT EXISTS MT_ETC_CODE (
    CODE_GROUP    TEXT NOT NULL,
    CODE          TEXT NOT NULL,
    CODE_NAME     TEXT NOT NULL,
    SORT_ORDER    INTEGER NOT NULL DEFAULT 0,
    USE_YN        TEXT NOT NULL DEFAULT 'Y',
    PRIMARY KEY (CODE_GROUP, CODE)
);

-- ---------------------------------------------------------------- 재고
CREATE TABLE IF NOT EXISTS INV_CENTER_STOCK (
    CENTER_CODE   TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    PRODUCT_CODE  TEXT NOT NULL REFERENCES MT_PRODUCT(PRODUCT_CODE),
    STOCK_QTY     INTEGER NOT NULL DEFAULT 0,
    UPDATED_AT    TEXT NOT NULL,
    PRIMARY KEY (CENTER_CODE, PRODUCT_CODE)
);

-- 단계별 입출고 이력 (STAGE: 입고/보관/피킹/패킹/출고)
CREATE TABLE IF NOT EXISTS INV_CENTER_INOUT_HISTORY (
    HISTORY_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    CENTER_CODE   TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    PRODUCT_CODE  TEXT NOT NULL REFERENCES MT_PRODUCT(PRODUCT_CODE),
    STAGE         TEXT NOT NULL,
    QTY           INTEGER NOT NULL,
    OCCURRED_AT   TEXT NOT NULL
);

-- 일별 입출고 집계 (단계별 처리량 포함 → 센터 화면 프로세스 플로우)
CREATE TABLE IF NOT EXISTS INV_CENTER_INOUT_DAILY (
    CENTER_CODE   TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    INOUT_DATE    TEXT NOT NULL,
    IN_QTY        INTEGER NOT NULL DEFAULT 0,   -- 입고
    STORAGE_QTY   INTEGER NOT NULL DEFAULT 0,   -- 보관(적치)
    PICKING_QTY   INTEGER NOT NULL DEFAULT 0,   -- 피킹
    PACKING_QTY   INTEGER NOT NULL DEFAULT 0,   -- 패킹
    OUT_QTY       INTEGER NOT NULL DEFAULT 0,   -- 출고
    PRIMARY KEY (CENTER_CODE, INOUT_DATE)
);

-- ---------------------------------------------------------------- 분석
CREATE TABLE IF NOT EXISTS AN_CENTER_KPI_DAILY (
    CENTER_CODE       TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    KPI_DATE          TEXT NOT NULL,
    ON_TIME_RATE      REAL NOT NULL,             -- 정시출고율(%)
    STOCK_QTY         INTEGER NOT NULL DEFAULT 0, -- 총 재고량
    SKU_COUNT         INTEGER NOT NULL DEFAULT 0, -- 보관 SKU 수
    OUTBOUND_WIP      INTEGER NOT NULL DEFAULT 0, -- 출고 진행 건
    UNRECEIVED_QTY    INTEGER NOT NULL DEFAULT 0, -- 미입고수량
    SHORTAGE_QTY      INTEGER NOT NULL DEFAULT 0, -- 미납수량
    ANOMALY_COUNT     INTEGER NOT NULL DEFAULT 0, -- 이상건수(상태이상)
    PRIMARY KEY (CENTER_CODE, KPI_DATE)
);

-- ---------------------------------------------------------------- 예외
-- EVENT_TYPE: 미납/미입고/상태이상, STATUS: 미처리/부분처리/처리완료
CREATE TABLE IF NOT EXISTS EXC_CENTER_EVENT (
    EVENT_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    CENTER_CODE   TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    PRODUCT_CODE  TEXT REFERENCES MT_PRODUCT(PRODUCT_CODE),
    EVENT_TYPE    TEXT NOT NULL,
    ANOMALY_TYPE  TEXT,                          -- 상태이상일 때 세부 유형
    EVENT_QTY     INTEGER NOT NULL DEFAULT 0,
    RESOLVED_QTY  INTEGER NOT NULL DEFAULT 0,
    STATUS        TEXT NOT NULL DEFAULT '미처리',
    OCCURRED_AT   TEXT NOT NULL,
    DUE_AT        TEXT NOT NULL,                 -- 조치 기한
    RESOLVED_AT   TEXT,
    NOTE          TEXT,
    CHECK (RESOLVED_QTY >= 0 AND RESOLVED_QTY <= EVENT_QTY)
);

CREATE TABLE IF NOT EXISTS EXC_CENTER_EVENT_RESOLVE (
    RESOLVE_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_ID      INTEGER NOT NULL REFERENCES EXC_CENTER_EVENT(EVENT_ID),
    ACTION_TYPE   TEXT NOT NULL,                 -- MT_ETC_CODE ACTION_TYPE
    ACTION_QTY    INTEGER NOT NULL,
    ACTION_NOTE   TEXT,
    RESOLVED_BY   TEXT,
    RESOLVED_AT   TEXT NOT NULL
);

-- ---------------------------------------------------------------- 워크플로우
-- STATUS: 지시완료 → 센터확인중 → 조치중 → 완료 (PRD 5)
-- SOURCE: 본사직접 / 에이전트초안
CREATE TABLE IF NOT EXISTS WF_INSTRUCTION (
    INSTRUCTION_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    CENTER_CODE     TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    TITLE           TEXT NOT NULL,
    BODY            TEXT NOT NULL,
    PRIORITY        TEXT NOT NULL DEFAULT '보통',  -- 보통/높음/긴급
    STATUS          TEXT NOT NULL DEFAULT '지시완료',
    SOURCE          TEXT NOT NULL DEFAULT '본사직접',
    DRAFT_ID        INTEGER REFERENCES WF_DRAFT(DRAFT_ID),
    CREATED_BY      TEXT NOT NULL DEFAULT '본사',
    CREATED_AT      TEXT NOT NULL,
    ACKNOWLEDGED_AT TEXT,
    REPORTED_AT     TEXT,
    APPROVED_AT     TEXT
);

CREATE TABLE IF NOT EXISTS WF_ACTION_REPORT (
    REPORT_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    INSTRUCTION_ID  INTEGER NOT NULL REFERENCES WF_INSTRUCTION(INSTRUCTION_ID),
    ACTION_TYPE     TEXT NOT NULL,
    REPORT_BODY     TEXT NOT NULL,
    REPORTED_BY     TEXT NOT NULL DEFAULT '센터',
    REPORTED_AT     TEXT NOT NULL,
    APPROVED_AT     TEXT,
    APPROVED_BY     TEXT
);

-- ---------------------------------------------------------------- 에이전트 추가 테이블
-- 모니터링/에이전트 실행 기록. MODE: agent/rules, STATUS: running/success/failed/skipped
CREATE TABLE IF NOT EXISTS AGENT_RUN (
    RUN_ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    TRIGGER        TEXT NOT NULL,               -- scheduler/manual/ui 등
    MODE           TEXT NOT NULL DEFAULT 'agent',
    STATUS         TEXT NOT NULL DEFAULT 'running',
    MODEL          TEXT,
    QUESTION       TEXT,
    SCOPE_CODES    TEXT,                        -- JSON 배열
    DETECTED_JSON  TEXT,                        -- 탐지 결과 JSON
    REPORT_JSON    TEXT,                        -- AgentReport JSON
    TOOL_LOG_JSON  TEXT,                        -- 도구 호출 로그 JSON
    SESSION_ID     TEXT,
    NUM_TURNS      INTEGER,
    COST_USD       REAL,
    DURATION_MS    INTEGER,
    ERROR_MESSAGE  TEXT,
    STARTED_AT     TEXT NOT NULL,
    FINISHED_AT    TEXT
);

-- 규칙 탐지 기록 (사이클마다 이상 센터 전부 기록, 대상 여부와 건너뜀 사유 포함)
CREATE TABLE IF NOT EXISTS MON_ALERT (
    ALERT_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    RUN_ID         INTEGER NOT NULL REFERENCES AGENT_RUN(RUN_ID),
    CENTER_CODE    TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    CENTER_STATUS  TEXT NOT NULL,               -- 주의/위험
    REASONS_JSON   TEXT NOT NULL,               -- 사유 목록 JSON
    FINGERPRINT    TEXT NOT NULL,
    TARGETED       INTEGER NOT NULL DEFAULT 0,  -- 1=에이전트 진단 대상
    SKIP_REASON    TEXT,
    DETECTED_AT    TEXT NOT NULL
);

-- 지시 초안 대기열. STATUS: 대기/승인/반려. 승인 시 WF_INSTRUCTION 1건 생성
CREATE TABLE IF NOT EXISTS WF_DRAFT (
    DRAFT_ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    RUN_ID            INTEGER REFERENCES AGENT_RUN(RUN_ID),
    CENTER_CODE       TEXT NOT NULL REFERENCES MT_CENTER(CENTER_CODE),
    TITLE             TEXT NOT NULL,
    BODY              TEXT NOT NULL,
    PRIORITY          TEXT NOT NULL DEFAULT '보통',
    EVIDENCE_IDS_JSON TEXT NOT NULL DEFAULT '[]',
    FINGERPRINT       TEXT NOT NULL,
    SOURCE            TEXT NOT NULL DEFAULT 'agent',  -- agent/rules
    STATUS            TEXT NOT NULL DEFAULT '대기',
    CREATED_AT        TEXT NOT NULL,
    DECIDED_AT        TEXT,
    DECIDED_BY        TEXT,
    DECISION_NOTE     TEXT,
    INSTRUCTION_ID    INTEGER REFERENCES WF_INSTRUCTION(INSTRUCTION_ID)
);

CREATE INDEX IF NOT EXISTS IX_EVENT_CENTER_STATUS ON EXC_CENTER_EVENT(CENTER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_INSTR_CENTER_STATUS ON WF_INSTRUCTION(CENTER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_DRAFT_STATUS ON WF_DRAFT(STATUS, CENTER_CODE);
CREATE INDEX IF NOT EXISTS IX_KPI_DATE ON AN_CENTER_KPI_DAILY(KPI_DATE);
